---

services:

  writer:
    build:
      context: .
      dockerfile: dockerWriter
    volumes:
      - data:/data
    command: ["writer.py", "/data/data.txt"]

  computer:
    build:
      context: .
      dockerfile: dockerComputer
    depends_on:
      - writer
    volumes:
      - data:/data
    command: ["python3.12", "/code/computer.py", "/data/data.txt", "/data/results.txt"]

  #webserver:
  #  build:
  #    context: .
  #    dockerfile: dockerHTML
  #  depends_on:
  #    - computer
  #  volumes:
  #    - data:/data
  #  ports:
  #    - "8000:8000"
  #  command: ["python3.12", "-m", "webserver.py", "EXPOSE 8000"]

volumes:
  data:
